#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: Iv1.e82a63a9ca2b4ac1
#            client-secret: e1bbe8cca8b7625c24e70aa9030d558f644d0568


spring:
  data:
    cassandra:
      keyspace-name: main
      username: YHqIEjuTiyMaQTwizPiLowjJ
      password: Oy_HqRB_ZAynM87+szyklxQwMc,1O0Wr1XK4ivrrHZAHo-JQpMLgHjIsg3vS+w5vQi,Wu1ujQ_dLBT+svav0gm1eBMEaDUUK.kYQDXMoerqjER+xg1fasKdx7IF1Zg+F
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  application:
    name: inbox-app
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.e82a63a9ca2b4ac1
            client-secret: e1bbe8cca8b7625c24e70aa9030d558f644d0568

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra:
  db:
    id: 5e654f7e-14bf-4048-96b7-a79d6cfc6fa1-1
    region: asia-south1
    keyspace: main
    application:
      token: AstraCS:YHqIEjuTiyMaQTwizPiLowjJ:b273efb07923a71f4c3ab12efe3c706502bbccbc3e12976f7a755367b5f7282c

